---
version: "3.7"
services:
  updater:
    image: qwtflive/updater:latest
    restart: always
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - S3_DEMO_URI
      - FO_REGION
      - CF_EMAIL
      - CF_TOKEN
      - CF_ZONE
      - TFL_HOST
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
      - pub-demos:/updater/demos/pub/
      - tourney-demos:/updater/demos/tourney/
      - scrim-demos:/updater/demos/scrim/
      - duel-demos:/updater/demos/duel/
      - staging-demos:/updater/demos/staging/
      - pub-stats:/updater/stats/pub/
      - tourney-stats:/updater/stats/tourney/
      - scrim-stats:/updater/stats/scrim/
      - duel-stats:/updater/stats/duel/
      - staging-stats:/updater/stats/staging/
    deploy:
      resources:
        limits:
          cpus: '0.10'
  pubserver:
    image: qwtflive/qwtfsv:latest
    network_mode: host
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27500
      +set hostname "${FO_HOSTNAME} Pub"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +set sv_serverip "${FO_IP}"
      +set net_mtu "${TFL_MTU:-1440}"
      +set timeout 10
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo discord_channel_id "${FO_DISCORD_CHANNEL_ID}"
      +localinfo backend_address "${FO_BACKEND_ADDRESS}"
      +localinfo shard "pub"
      +exec fo_pubmode.cfg
      +map 2fort5r
    volumes:
      - assets:/qwtfsv/fortress/assets/
      - master_dats:/qwtfsv/fortress/dats/
      - pub-demos:/qwtfsv/fortress/demos/
      - pub-stats:/qwtfsv/fortress/data/
  duelserver:
    image: qwtflive/qwtfsv:latest
    network_mode: host
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27501
      +set hostname "${FO_HOSTNAME} Duel"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +set sv_serverip "${FO_IP}:27501"
      +set net_mtu "${TFL_MTU:-1440}"
      +set timeout 10
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo discord_channel_id "${FO_DISCORD_CHANNEL_ID}"
      +localinfo backend_address "${FO_BACKEND_ADDRESS}"
      +localinfo shard "duel"
      +exec fo_duelmode.cfg
      +map 1on1r
    volumes:
      - assets:/qwtfsv/fortress/assets/
      - master_dats:/qwtfsv/fortress/dats/
      - duel-demos:/qwtfsv/fortress/demos/
      - duel-stats:/qwtfsv/fortress/data/
  tourneyserver:
    image: qwtflive/qwtfsv:latest
    network_mode: host
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27504
      +set hostname "${FO_HOSTNAME} Tourney"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +set sv_serverip "${FO_IP}:27504"
      +set net_mtu "${TFL_MTU:-1440}"
      +set timeout 10
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo discord_channel_id 1026405619231625257
      +localinfo backend_address "${FO_BACKEND_ADDRESS}"
      +localinfo shard "tourney"
      +exec fo_quadmode.cfg
      +map 2fort5r
    volumes:
      - assets:/qwtfsv/fortress/assets/
      - master_dats:/qwtfsv/fortress/dats/
      - tourney-demos:/qwtfsv/fortress/demos/
      - tourney-stats:/qwtfsv/fortress/data/
  scrimserver:
    image: qwtflive/qwtfsv:latest
    network_mode: host
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27505
      +set hostname "${FO_HOSTNAME} Scrim"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +set sv_serverip "${FO_IP}:27505"
      +set net_mtu "${TFL_MTU:-1440}"
      +set timeout 10
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo discord_channel_id 1147341454851719219
      +localinfo backend_address "${FO_BACKEND_ADDRESS}"
      +localinfo shard "scrim"
      +exec fo_quadmode.cfg
      +map 2fort5r
    volumes:
      - assets:/qwtfsv/fortress/assets/
      - staging_dats:/qwtfsv/fortress/dats/
      - scrim-demos:/qwtfsv/fortress/demos/
      - scrim-stats:/qwtfsv/fortress/data/
  stagingserver:
    image: qwtflive/qwtfsv:latest
    network_mode: host
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27510
      +set hostname "${FO_HOSTNAME} Staging"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +set sv_serverip "${FO_IP}:27510"
      +set net_mtu "${TFL_MTU:-1440}"
      +set timeout 10
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo discord_channel_id "${FO_DISCORD_CHANNEL_ID}"
      +localinfo backend_address "${FO_BACKEND_ADDRESS}"
      +localinfo shard "staging"
      +exec fo_stagingmode.cfg
      +map 2fort5r
    volumes:
      - assets:/qwtfsv/fortress/assets/
      - staging_dats:/qwtfsv/fortress/dats/
      - staging-demos:/qwtfsv/fortress/demos/
      - staging-stats:/qwtfsv/fortress/data/
  qwfwd:
    image: fortressone/qwfwd:latest
    network_mode: host
    stdin_open: true
    tty: true
    restart: always
    command: |
      30000 0.0.0.0
      +set hostname "${FO_HOSTNAME} QWfwd"
volumes:
  pub-demos:
  duel-demos:
  tourney-demos:
  scrim-demos:
  staging-demos:
  pub-stats:
  duel-stats:
  tourney-stats:
  scrim-stats:
  staging-stats:
  assets:
  master_dats:
  staging_dats:
