#!/usr/bin/env bash

set -e
set -u

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "$DIR/shared"

source_and_update () {
  source_docker_host "${1}"
  source_docker_compose_env "${1}"
  docker compose exec updater /updater/sync.sh
}

for m in "${aws_machines[@]}"
do
  echo Updating "${m}"
  (
  source_aws_env "${m}"
  source_and_update "${m}"
  )
done

for m in "${other_machines[@]}"
do
  echo Updating "${m}"
  (
  source_and_update "${m}"
  )
done
